[project]
name = "demo-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.119.1",
    "fastmcp>=2.12.5",
    "requests>=2.32.5",
    "uvicorn>=0.38.0",
]
